### PR TITLE
[INTERNAL] JSDoc generation: enable links with prefix 'demo:'

### PR DESCRIPTION
**Pull request by flovogt**
**Thank you for your contribution!** 🙌

To get it merged faster, kindly review the checklist below:

## Pull Request Checklist
- [x] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-tooling/blob/master/CONTRIBUTING.md#-contributing-code)
    + Especially the [How to Contribute](https://github.com/SAP/ui5-tooling/blob/master/CONTRIBUTING.md#how-to-contribute) section 
- [x] [No merge commits](https://github.com/SAP/ui5-tooling/blob/master/docs/Guidelines.md#no-merge-commits)
- [x] [Correct commit message style](https://github.com/SAP/ui5-tooling/blob/master/docs/Guidelines.md#commit-message-style)

### CODE REVIEW

**Comment by flovogt** [comment]
Allows using the following JSDoc syntax {@link demo:my/module/page/demo.html My Demo}

**Comment by matz3** [comment]
Do we need this in v2.x or just in v3.x?

**Review by matz3 — APPROVED** [review]

**Comment by matz3** [comment]
Please squash and merge this PR and then cherry-pick the merged commit to a new PR for the `next` branch.

**Comment by flovogt** [comment]
> Do we need this in v2.x or just in v3.x?

Yes in both as long as we use v2 in the openui5 project.

**Pull request merged**
