### PR TITLE
[INTERNAL] package.json: Increase test timeout to 2 minutes (xunit only)

### PR DESCRIPTION
**Pull request by RandomByte**
Hopefully this will reduce the number of random failures on Windows on
Azure. Presumably they are caused by some sort of timeout within AVA.

### CODE REVIEW

**Comment by matz3** [comment]
Still failing. Let's try to increase the 10s timeout to 1 minute

**Review by matz3 — DISMISSED** [review]
I'd say let's try whether this works in the long term

**Comment by RandomByte** [comment]
I re-triggered your commit two times and all executions where successful. But let's try whether the serial flag makes any immediate difference.

**Comment by RandomByte** [comment]
Seems to be stable as well. I would squash and merge this, so it's basically just your commit @matz3. What do you think?

**Comment by matz3** [comment]
👍🏻

**Review by matz3 — APPROVED** [review]

**Pull request merged**
