### PR TITLE
[INTERNAL] Disable special core handling if project contains bundle config

### PR DESCRIPTION
**Pull request by matz3**

### CODE REVIEW

**Review by RandomByte — APPROVED** [review]
We should execute a smoke test for this

**Comment by matz3** [comment]
Smoke Test Build #731 started

**Comment by matz3** [comment]
I've also manually verified the change with the openui5-sample-app and the current sap.ui.core library (1.97.0-SNAPSHOT).

**Comment by matz3** [comment]
Smoke Test did not show any issues related to this change.

**Pull request merged**
