### PR TITLE
[INTERNAL] In-range update of npm dependencies + fix terser tests

### PR DESCRIPTION
**Pull request by RandomByte**
See https://github.com/terser/terser/blob/master/CHANGELOG.md#v430

> Functions passed to other functions in calls are now wrapped in
> parentheses by default, which speeds up loading most modules

### CODE REVIEW

**Comment by codeworrior** [comment]
Instead of adapting the tests, we IMO better should set the new option [`wrap_func_args`](https://github.com/terser/terser) to `false`.

**Comment by RandomByte** [comment]
Sorry, I put that information in the second commit and forgot to edit the PR info.

Terser added a new `wrap_func_args` parameter which defaults to true.
PR implementing it: https://github.com/terser/terser/pull/433
Documentation: https://github.com/terser/terser#output-options => `wrap_func_args` (which refers to https://github.com/nolanlawson/optimize-js)

**Comment by codeworrior** [comment]
Okay, only now I read your initial comment, so you have been aware of the change.

In my opinion, the opposite is true for UI5. Our library preloads rely on lazy parsing. Only when lazy parsing is used, loading the huge preloads isn't too bad as the browser only parses and compiles what's needed. 

But when we force eager parsing by adding the parentheses, all functions will be parsed and compiled after loading a library-preload. Measurements in the past have shown that this makes a very significant difference for the startup times of UI5 apps.

**Comment by codeworrior** [comment]
@pskelin can you confirm that eager parsing would be a severe drawback for UI5 library preloads, after all we know?

**Comment by RandomByte** [comment]
Alternative PR, setting tersers `wrap_func_args` option to false: https://github.com/SAP/ui5-builder/pull/331

**Pull request closed without merging**
