### PR TITLE
[FEATURE] Support ES2021 language features

### PR DESCRIPTION
**Pull request by matz3**
By upgrading espree to the latest version, ES2021 language features
are now supported.

JIRA: CPOUI5FOUNDATION-363

### CODE REVIEW

**Review by RandomByte — COMMENTED** [review]
LGTM, @codeworrior to approve

**Comment by codeworrior** [comment]
I have to make up my mind how to properly handle chained expressions. Our check for conditional expressions wants to detect whether a certain code is always executed (eager) or not (conditional).

The following top level code
```
someName.memberA[(function() { sap.ui.require(["a/b/c"]); return "someProperty";}())] 
```
would eagerly depend on a/b/c.

But
```
someName.memberA?.[(function() { sap.ui.require(["a/b/c"]); return "someProperty";}())] 
```
would not. 

This no longer can be declared statically. Within a ChainExpression.expression, the optional flag of the contained MemberExpressions has to be taken into account. If it is true, then the property part becomes conditional.

Well, but to enable the new syntax elements, the change is both required and helpful.

**Review by codeworrior — APPROVED** [review]

**Comment by matz3** [comment]
Thanks for the insights.

I also thought about handling for the ChainExpression.
But as e.g. `someName.memberA && sap.ui.require(["a/b/c"]);` will not result into a conditional dependency, I thought that we anyways have some cases where we could improve, so I didn't have a deeper look into all this.

What I forgot to mention:
ChainExpression is not part of the `Syntax`, so I first could run a build without any issues until I used a ChainExpression in the code, which resulted into an error in the JSModuleAnalyzer visit function ("Unhandled AST node type"). So maybe we need another check in the opposite direction, at least within a unit test, to ensure that we will add new node types to our code.

**Comment by codeworrior** [comment]
Reg. the gaps in _espree.Syntax_ see https://github.com/eslint/espree/pull/532 (fixes https://github.com/eslint/espree/issues/531)

I'm waiting for OSPO to approve the (C)CLA.

**Comment by pubmikeb** [comment]
Does this merge mean that UI5 Tooling 2.14.5 now supports the ES2021 language features?

**Comment by matz3** [comment]
@pubmikeb this PR got merged into the `next` branch which will result into the `v3.0.0` release. There are prereleases available, as described in https://github.com/SAP/ui5-tooling/issues/506

As the espree update requires a higher node version, we are not able to port this into the v2.x codeline.

**Pull request merged**
