### PR TITLE
[DEPENDENCY] Switch from "rimraf" to native "fs.rm"

### PR DESCRIPTION
**Pull request by matz3**

### CODE REVIEW

**Review by codeworrior — DISMISSED** [review]
It took me a while to understand suffix "p" in "mkdirp", but "rmrf" finally explained it :-)

**Comment by matz3** [comment]
As `rimraf` still uses its own implementation on Windows, I want to do some manual testing before merging this. Our unit tests don't cover this part well as many times the FS APIs are stubbed.

**Comment by matz3** [comment]
I've tested this on Windows via `ui5 build --all --clean-dest` and `ui5 build jsdoc --all --clean-dest` and didn't see any issues. So I'm eager to merge this.

Also see https://github.com/SAP/ui5-project/pull/780

**Review by codeworrior — APPROVED** [review]
LGTM

**Review by RandomByte — APPROVED** [review]

**Comment by matz3** [comment]
I forgot to adjust the commit message via squash merge. The merged commit on main has been adjusted as 0adf4da0e747f1fb46cf0bf0da7b3e0af8e9bcec.

**Pull request merged**
